const CAPTURE = {
    tick: {
        MatchGuid: 'A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6',
        Players: [
            {
                Name: 'PlayerA',
                PrimaryId: 'Steam|76561190000000000|0',
                Shortcut: 5,
                TeamNum: 1,
                Score: 178,
                Goals: 1,
                Shots: 1,
                Assists: 1,
                Saves: 0,
                Touches: 13,
                CarTouches: 11,
                Demos: 0,
                Loadout: [
                    'body_grain',
                    'skin_10x',
                    'Wheel_SoccerBall',
                    'boost_aurum',
                    'None',
                    'hat_kitty',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'EngineAudio_Grain',
                    'ss_glitchbolt',
                    'Explosion_Default',
                    'playerbanner_courgette',
                    'None',
                    'anthem_hiphopclassicsvol1_02',
                    'None',
                    'avatarborder_rivals',
                    'Jynxzi_BALRIGHT',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                ],
                bOnGround: true,
                bHasCar: true,
                Speed: 0.009755998849868774,
                Boost: 33,
                PickupClass: 'None',
            },
            {
                Name: 'PlayerB',
                PrimaryId: 'Unknown|0|0',
                Shortcut: 1,
                TeamNum: 0,
                Score: 4,
                Goals: 0,
                Shots: 0,
                Assists: 0,
                Saves: 0,
                Touches: 6,
                CarTouches: 43,
                Demos: 0,
                Loadout: [
                    'Body_Backfire',
                    'Skin_Backfire_Flames',
                    'WHEEL_Crypt',
                    'Boost_Flamethrower',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'ss_default',
                    'Explosion_Default',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                ],
                bOnGround: true,
                bHasCar: true,
                Speed: 50.4423828125,
                Boost: 100,
                PickupClass: 'None',
            },
            {
                Name: 'PlayerC',
                PrimaryId: 'Unknown|0|0',
                Shortcut: 2,
                TeamNum: 0,
                Score: 74,
                Goals: 0,
                Shots: 0,
                Assists: 1,
                Saves: 0,
                Touches: 8,
                CarTouches: 67,
                Demos: 0,
                Loadout: [
                    'Body_Torment',
                    'Skin_Torment_Flames',
                    'WHEEL_Crypt',
                    'Boost_Standard',
                    'Antenna_Horseshoe',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'ss_default',
                    'Explosion_Default',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                ],
                bOnGround: true,
                bHasCar: true,
                Speed: 6.512521266937256,
                Boost: 11,
                bBoosting: true,
                PickupClass: 'None',
            },
            {
                Name: 'PlayerD',
                PrimaryId: 'Unknown|0|0',
                Shortcut: 6,
                TeamNum: 1,
                Score: 118,
                Goals: 1,
                Shots: 1,
                Assists: 0,
                Saves: 0,
                Touches: 8,
                CarTouches: 74,
                Demos: 0,
                Loadout: [
                    'Body_Spark',
                    'Skin_Spark_Stripes',
                    'WHEEL_LowRider',
                    'Boost_Standard',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'ss_default',
                    'Explosion_Default',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                ],
                bOnGround: true,
                bHasCar: true,
                Speed: 29.376981735229492,
                Boost: 12,
                PickupClass: 'None',
            },
            {
                Name: 'PlayerE',
                PrimaryId: 'Unknown|0|0',
                Shortcut: 3,
                TeamNum: 0,
                Score: 116,
                Goals: 1,
                Shots: 1,
                Assists: 0,
                Saves: 0,
                Touches: 4,
                CarTouches: 63,
                Demos: 0,
                Loadout: [
                    'Body_Vanquish',
                    'Skin_Vanquish_Lightning',
                    'WHEEL_Vortex',
                    'Boost_Standard_Blue',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'ss_default',
                    'Explosion_Default',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                ],
                bOnGround: true,
                bHasCar: true,
                Speed: 15.719786643981934,
                Boost: 8,
                PickupClass: 'None',
            },
            {
                Name: 'PlayerF',
                PrimaryId: 'Unknown|0|0',
                Shortcut: 7,
                TeamNum: 1,
                Score: 0,
                Goals: 0,
                Shots: 0,
                Assists: 0,
                Saves: 0,
                Touches: 3,
                CarTouches: 46,
                Demos: 0,
                Loadout: [
                    'Body_Rhino',
                    'Skin_Rhino_Flames',
                    'WHEEL_DeepDish',
                    'Boost_Propulsion_Yellow',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'ss_default',
                    'Explosion_Default',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                    'None',
                ],
                bOnGround: true,
                bHasCar: true,
                Speed: 50.21567916870117,
                Boost: 55,
                PickupClass: 'None',
            },
        ],
        Game: {
            Teams: [
                {
                    Name: 'PlayerG',
                    TeamNum: 0,
                    Score: 1,
                    ColorPrimary: '1873FF',
                    ColorSecondary: 'E5E5E5',
                },
                {
                    Name: 'PlayerH',
                    TeamNum: 1,
                    Score: 2,
                    ColorPrimary: 'C26418',
                    ColorSecondary: 'E5E5E5',
                },
            ],
            PlaylistId: 6,
            TimeSeconds: 80,
            bOvertime: false,
            Ball: {
                Speed: 19.1461238861084,
                TeamNum: 0,
            },
            bReplay: true,
            bHasWinner: false,
            Winner: '',
            Arena: 'STADIUM_10A_P',
            bHasTarget: false,
        },
    },
    goal: {
        MatchGuid: 'A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6',
        GoalSpeed: 0,
        GoalTime: 0,
        ImpactLocation: {
            X: 266.4422607421875,
            Y: 5234.12109375,
            Z: 93.51434326171875,
        },
        Scorer: {
            Name: '',
            Shortcut: 0,
            TeamNum: 0,
        },
        BallLastTouch: {
            Player: {
                Name: 'PlayerE',
                Shortcut: 3,
                TeamNum: 0,
            },
            Speed: 32.030792236328125,
        },
    },
    ballhit: {
        MatchGuid: 'A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6',
        Players: [
            {
                Name: 'PlayerD',
                Shortcut: 6,
                TeamNum: 1,
            },
            {
                Name: 'PlayerB',
                Shortcut: 1,
                TeamNum: 0,
            },
        ],
        Ball: {
            PreHitSpeed: 0,
            PostHitSpeed: 80.25428009033203,
            Location: {
                X: -5.55189847946167,
                Y: 74.88462829589844,
                Z: 92.86334228515625,
            },
        },
    },
    statfeed: {
        MatchGuid: 'A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6',
        EventName: 'Shot',
        Type: 'Shot on Goal',
        MainTarget: {
            Name: 'PlayerF',
            Shortcut: 7,
            TeamNum: 1,
        },
    },
} as const;

export const LIVE_TICK = CAPTURE.tick;
export const LIVE_GOAL = CAPTURE.goal;
export const LIVE_BALL_HIT = CAPTURE.ballhit;
export const LIVE_STATFEED = CAPTURE.statfeed;

export function liveFrame(event: string, data: unknown): string {
    return JSON.stringify({ Event: event, Data: JSON.stringify(data) });
}
